---
all:
  children:
    netbox_servers:
      hosts:
        netbox:
          ansible_host: 10.0.150.139
          ansible_user: root

    database_servers:
      hosts:
        postgresql:
          ansible_host: 10.0.150.130
          ansible_user: root
