---
baseline_timezone: America/Chicago
baseline_locale: en_US.UTF-8
baseline_upgrade_packages: true

baseline_packages:
  - ca-certificates
  - curl
  - git
  - gnupg
  - htop
  - jq
  - locales
  - openssh-server
  - rsync
  - unzip
  - vim
  - wget
